# Generated by Django 2.1.5 on 2019-03-10 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTermRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('text', models.TextField()),
                ('ticketID', models.ForeignKey(on_delete='CASCADE', related_name='ticket_history', to='tickets.Ticket')),
                ('toWhom', models.ForeignKey(null=True, on_delete='CASCADE', related_name='destination', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete='CASCADE', related_name='origin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
