# Generated by Django 2.1.4 on 2018-12-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(auto_created=True, db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reports',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='term',
            field=models.DateField(),
        ),
    ]
