# Generated by Django 2.1.4 on 2018-12-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20181217_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='term',
            field=models.DateField(),
        ),
    ]
