# Generated by Django 2.1.4 on 2018-12-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20181217_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='was_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(max_length=50, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fathname',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=150, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondname',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
