# Generated by Django 2.1.4 on 2018-12-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20181218_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='controlGK',
            field=models.BooleanField(default=False, verbose_name='Контроль генерального'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ManyToManyField(related_name='Потребитель', to='tickets.User'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='job',
            field=models.TextField(db_index=True, verbose_name='Вид работ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='osn',
            field=models.CharField(max_length=150, verbose_name='Основание'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reports',
            field=models.TextField(blank=True, max_length=200, verbose_name='Отчетные материалы'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='responsible',
            field=models.ManyToManyField(related_name='Ответственый', to='tickets.User'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='term',
            field=models.DateField(verbose_name='Срок'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='theme',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='zakaz',
            field=models.CharField(max_length=50, verbose_name='Заказ'),
        ),
    ]
