# Generated by Django 2.1.4 on 2018-12-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20181218_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='was_read',
            new_name='isRead',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('active', 'действующая'), ('closed', 'закрыта'), ('prolong', 'продлена'), ('copy', 'копия')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
